cd ../samples/
mv sample_AAACGG.fq sample_FEM007.fq
mv sample_AACGTT.fq sample_FEM012.fq
mv sample_AACTGA.fq sample_FEM038.fq
mv sample_AAGACG.fq sample_FEM040.fq
mv sample_AAGCTA.fq sample_FEM042.fq
mv sample_AATATC.fq sample_FEM043.fq
mv sample_AATGAG.fq sample_FEM044.fq
mv sample_ACAAGA.fq sample_FEM045.fq
mv sample_ACAGCG.fq sample_FEM048.fq
mv sample_ACATAC.fq sample_FEM049.fq
mv sample_ACCATG.fq sample_FEM050.fq
mv sample_ACCCCC.fq sample_FEM053.fq
mv sample_ACTCTT.fq sample_FEM054.fq
mv sample_ACTGGC.fq sample_FEM055.fq
mv sample_AGCCAT.fq sample_FEM057.fq
mv sample_AGCGCA.fq sample_FEM059.fq
mv sample_AGGGTC.fq sample_FEM060.fq
mv sample_AGGTGT.fq sample_FEM061.fq
mv sample_AGTAGG.fq sample_FEM062.fq
mv sample_AGTTAA.fq sample_FEM063.fq
mv sample_ATAGTA.fq sample_FEM065.fq
mv sample_ATCAAA.fq sample_FEM068.fq
mv sample_ATGCAC.fq sample_FEM069.fq
mv sample_ATGTTG.fq sample_FEM070.fq
mv sample_ATTCCG.fq sample_FEM071.fq
mv sample_CAAAAA.fq sample_FEM073.fq
mv sample_CAATCG.fq sample_FEM075.fq
mv sample_CACCTC.fq sample_FEM079.fq
mv sample_CAGGCA.fq sample_FEM085.fq
mv sample_CATACT.fq sample_FEM086.fq
mv sample_CCATTT.fq sample_PRM035.fq
mv sample_CCCGGT.fq sample_PRM040.fq
mv sample_CCCTAA.fq sample_PRM052.fq
mv sample_CCGAGG.fq sample_PRM063.fq
mv sample_CCGCAT.fq sample_PRM075.fq
mv sample_CCTAAC.fq sample_PRM094.fq
mv sample_CGAGGC.fq sample_PRM095.fq
mv sample_CGCAGA.fq sample_PRM116.fq
mv sample_CGCGTG.fq sample_PRM123.fq
mv sample_CGGTCC.fq sample_PRM135-1.fq
mv sample_CGTCTA.fq sample_PRM138.fq
mv sample_CGTGAT.fq sample_PRM141.fq
mv sample_CTACAG.fq sample_PRM142.fq
mv sample_CTCGCC.fq sample_PRM157.fq
mv sample_CTGCGA.fq sample_PRM158.fq
mv sample_CTGGTT.fq sample_PRM170.fq
mv sample_CTTATG.fq sample_PRM180.fq
mv sample_CTTTGC.fq sample_PRM024.fq
mv sample_TCTTCT.fq sample_PRM027.fq
mv sample_TGAACC.fq sample_PRM029.fq
mv sample_TGACAA.fq sample_PRM030.fq
mv sample_TGCCCG.fq sample_PRM031.fq
mv sample_TGCTTA.fq sample_PRM032.fq
mv sample_TGGGGA.fq sample_PRM033.fq
mv sample_TTATGA.fq sample_PRM034.fq
mv sample_TTCCGT.fq sample_PRM035-2.fq
mv sample_TTCTAG.fq sample_PRM036.fq
mv sample_TTGAGC.fq sample_PRM037.fq
mv sample_TTTAAT.fq sample_PRM038.fq
mv sample_TTTGTC.fq sample_PRM039.fq
