cd ../samples/PstI/
mv sample_AAACGG.fq orad_FEM007.fq
mv sample_AACGTT.fq orad_FEM012.fq
mv sample_AACTGA.fq orad_FEM038.fq
mv sample_AAGACG.fq orad_FEM040.fq
mv sample_AAGCTA.fq orad_FEM042.fq
mv sample_AATATC.fq orad_FEM043.fq
mv sample_AATGAG.fq orad_FEM044.fq
mv sample_ACAAGA.fq orad_FEM045.fq
mv sample_ACAGCG.fq orad_FEM048.fq
mv sample_ACATAC.fq orad_FEM049.fq
mv sample_ACCATG.fq orad_FEM050.fq
mv sample_ACCCCC.fq orad_FEM053.fq
mv sample_ACTCTT.fq orad_FEM054.fq
mv sample_ACTGGC.fq orad_FEM055.fq
mv sample_AGCCAT.fq orad_FEM057.fq
mv sample_AGCGCA.fq orad_FEM059.fq
mv sample_AGGGTC.fq orad_FEM060.fq
mv sample_AGGTGT.fq orad_FEM061.fq
mv sample_AGTAGG.fq orad_FEM062.fq
mv sample_AGTTAA.fq orad_FEM063.fq
mv sample_ATAGTA.fq orad_FEM065.fq
mv sample_ATCAAA.fq orad_FEM068.fq
mv sample_ATGCAC.fq orad_FEM069.fq
mv sample_ATGTTG.fq orad_FEM070.fq
mv sample_ATTCCG.fq orad_FEM071.fq
mv sample_CAAAAA.fq orad_FEM073.fq
mv sample_CAATCG.fq orad_FEM075.fq
mv sample_CACCTC.fq orad_FEM079.fq
mv sample_CAGGCA.fq orad_FEM085.fq
mv sample_CATACT.fq orad_FEM086.fq
mv sample_CCATTT.fq orad_PRM351.fq
mv sample_CCCGGT.fq orad_PRM040.fq
mv sample_CCCTAA.fq orad_PRM052.fq
mv sample_CCGAGG.fq orad_PRM063.fq
mv sample_CCGCAT.fq orad_PRM075.fq
mv sample_CCTAAC.fq orad_PRM094.fq
mv sample_CGAGGC.fq orad_PRM095.fq
mv sample_CGCAGA.fq orad_PRM116.fq
mv sample_CGCGTG.fq orad_PRM123.fq
mv sample_CGGTCC.fq orad_PRM135.fq
mv sample_CGTCTA.fq orad_PRM138.fq
mv sample_CGTGAT.fq orad_PRM141.fq
mv sample_CTACAG.fq orad_PRM142.fq
mv sample_CTCGCC.fq orad_PRM157.fq
mv sample_CTGCGA.fq orad_PRM158.fq
mv sample_CTGGTT.fq orad_PRM170.fq
mv sample_CTTATG.fq orad_PRM180.fq
mv sample_CTTTGC.fq orad_PRM024.fq
mv sample_TCTTCT.fq orad_PRM027.fq
mv sample_TGAACC.fq orad_PRM029.fq
mv sample_TGACAA.fq orad_PRM030.fq
mv sample_TGCCCG.fq orad_PRM031.fq
mv sample_TGCTTA.fq orad_PRM032.fq
mv sample_TGGGGA.fq orad_PRM033.fq
mv sample_TTATGA.fq orad_PRM034.fq
mv sample_TTCCGT.fq orad_PRM325.fq
mv sample_TTCTAG.fq orad_PRM036.fq
mv sample_TTGAGC.fq orad_PRM037.fq
mv sample_TTTAAT.fq orad_PRM038.fq
mv sample_TTTGTC.fq orad_PRM039.fq
