cd ../samples/
samtools view -bS sample_FEM001_align.sam > sample_FEM001_align.bam
samtools view -bS sample_FEM002_align.sam > sample_FEM002_align.bam
samtools view -bS sample_FEM004_align.sam > sample_FEM004_align.bam
samtools view -bS sample_FEM005_align.sam > sample_FEM005_align.bam
samtools view -bS sample_FEM006_align.sam > sample_FEM006_align.bam
samtools view -bS sample_FEM007_align.sam > sample_FEM007_align.bam
samtools view -bS sample_FEM008_align.sam > sample_FEM008_align.bam
samtools view -bS sample_FEM009_align.sam > sample_FEM009_align.bam
samtools view -bS sample_FEM010_align.sam > sample_FEM010_align.bam
samtools view -bS sample_FEM011_align.sam > sample_FEM011_align.bam
samtools view -bS sample_FEM012_align.sam > sample_FEM012_align.bam
samtools view -bS sample_FEM013_align.sam > sample_FEM013_align.bam
samtools view -bS sample_FEM014_align.sam > sample_FEM014_align.bam
samtools view -bS sample_FEM015_align.sam > sample_FEM015_align.bam
samtools view -bS sample_FEM016_align.sam > sample_FEM016_align.bam
samtools view -bS sample_FEM017_align.sam > sample_FEM017_align.bam
samtools view -bS sample_FEM018_align.sam > sample_FEM018_align.bam
samtools view -bS sample_FEM019_align.sam > sample_FEM019_align.bam
samtools view -bS sample_FEM020_align.sam > sample_FEM020_align.bam
samtools view -bS sample_FEM021_align.sam > sample_FEM021_align.bam
samtools view -bS sample_FEM022_align.sam > sample_FEM022_align.bam
samtools view -bS sample_FEM023_align.sam > sample_FEM023_align.bam
samtools view -bS sample_FEM024_align.sam > sample_FEM024_align.bam
samtools view -bS sample_FEM025_align.sam > sample_FEM025_align.bam
samtools view -bS sample_FEM026_align.sam > sample_FEM026_align.bam
samtools view -bS sample_FEM027_align.sam > sample_FEM027_align.bam
samtools view -bS sample_FEM028_align.sam > sample_FEM028_align.bam
samtools view -bS sample_FEM029_align.sam > sample_FEM029_align.bam
samtools view -bS sample_FEM030_align.sam > sample_FEM030_align.bam
samtools view -bS sample_FEM031_align.sam > sample_FEM031_align.bam
samtools view -bS sample_FEM032_align.sam > sample_FEM032_align.bam
samtools view -bS sample_FEM033_align.sam > sample_FEM033_align.bam
samtools view -bS sample_FEM034_align.sam > sample_FEM034_align.bam
samtools view -bS sample_FEM035_align.sam > sample_FEM035_align.bam
samtools view -bS sample_FEM036_align.sam > sample_FEM036_align.bam
samtools view -bS sample_FEM037_align.sam > sample_FEM037_align.bam
samtools view -bS sample_FEM038_align.sam > sample_FEM038_align.bam
samtools view -bS sample_FEM039_align.sam > sample_FEM039_align.bam
samtools view -bS sample_FEM040_align.sam > sample_FEM040_align.bam
samtools view -bS sample_FEM041_align.sam > sample_FEM041_align.bam
samtools view -bS sample_FEM042_align.sam > sample_FEM042_align.bam
samtools view -bS sample_FEM043_align.sam > sample_FEM043_align.bam
samtools view -bS sample_FEM044_align.sam > sample_FEM044_align.bam
samtools view -bS sample_FEM045_align.sam > sample_FEM045_align.bam
samtools view -bS sample_FEM046_align.sam > sample_FEM046_align.bam
samtools view -bS sample_FEM047_align.sam > sample_FEM047_align.bam
samtools view -bS sample_FEM048_align.sam > sample_FEM048_align.bam
samtools view -bS sample_FEM049_align.sam > sample_FEM049_align.bam
samtools view -bS sample_FEM050_align.sam > sample_FEM050_align.bam
samtools view -bS sample_FEM051_align.sam > sample_FEM051_align.bam
samtools view -bS sample_FEM052_align.sam > sample_FEM052_align.bam
samtools view -bS sample_FEM053_align.sam > sample_FEM053_align.bam
samtools view -bS sample_FEM054-1_align.sam > sample_FEM054-1_align.bam
samtools view -bS sample_FEM054_align.sam > sample_FEM054_align.bam
samtools view -bS sample_FEM055_align.sam > sample_FEM055_align.bam
samtools view -bS sample_FEM056_align.sam > sample_FEM056_align.bam
samtools view -bS sample_FEM057_align.sam > sample_FEM057_align.bam
samtools view -bS sample_FEM058_align.sam > sample_FEM058_align.bam
samtools view -bS sample_FEM059_align.sam > sample_FEM059_align.bam
samtools view -bS sample_FEM060_align.sam > sample_FEM060_align.bam
samtools view -bS sample_FEM061_align.sam > sample_FEM061_align.bam
samtools view -bS sample_FEM062_align.sam > sample_FEM062_align.bam
samtools view -bS sample_FEM063_align.sam > sample_FEM063_align.bam
samtools view -bS sample_FEM064_align.sam > sample_FEM064_align.bam
samtools view -bS sample_FEM065_align.sam > sample_FEM065_align.bam
samtools view -bS sample_FEM066_align.sam > sample_FEM066_align.bam
samtools view -bS sample_FEM067_align.sam > sample_FEM067_align.bam
samtools view -bS sample_FEM068_align.sam > sample_FEM068_align.bam
samtools view -bS sample_FEM069_align.sam > sample_FEM069_align.bam
samtools view -bS sample_FEM070_align.sam > sample_FEM070_align.bam
samtools view -bS sample_FEM071_align.sam > sample_FEM071_align.bam
samtools view -bS sample_FEM072_align.sam > sample_FEM072_align.bam
samtools view -bS sample_FEM073_align.sam > sample_FEM073_align.bam
samtools view -bS sample_FEM074_align.sam > sample_FEM074_align.bam
samtools view -bS sample_FEM075_align.sam > sample_FEM075_align.bam
samtools view -bS sample_FEM076_align.sam > sample_FEM076_align.bam
samtools view -bS sample_FEM077_align.sam > sample_FEM077_align.bam
samtools view -bS sample_FEM078_align.sam > sample_FEM078_align.bam
samtools view -bS sample_FEM079_align.sam > sample_FEM079_align.bam
samtools view -bS sample_FEM080_align.sam > sample_FEM080_align.bam
samtools view -bS sample_FEM081_align.sam > sample_FEM081_align.bam
samtools view -bS sample_FEM082_align.sam > sample_FEM082_align.bam
samtools view -bS sample_FEM083_align.sam > sample_FEM083_align.bam
samtools view -bS sample_FEM084_align.sam > sample_FEM084_align.bam
samtools view -bS sample_FEM085_align.sam > sample_FEM085_align.bam
samtools view -bS sample_FEM086_align.sam > sample_FEM086_align.bam
samtools view -bS sample_FEM087_align.sam > sample_FEM087_align.bam
samtools view -bS sample_NPM005_align.sam > sample_NPM005_align.bam
samtools view -bS sample_NPM006_align.sam > sample_NPM006_align.bam
samtools view -bS sample_NPM007_align.sam > sample_NPM007_align.bam
samtools view -bS sample_NPM008_align.sam > sample_NPM008_align.bam
samtools view -bS sample_NPM010_align.sam > sample_NPM010_align.bam
samtools view -bS sample_NPM011_align.sam > sample_NPM011_align.bam
samtools view -bS sample_NPM012_align.sam > sample_NPM012_align.bam
samtools view -bS sample_NPM1128_align.sam > sample_NPM1128_align.bam
samtools view -bS sample_OFF001_align.sam > sample_OFF001_align.bam
samtools view -bS sample_OFF004_align.sam > sample_OFF004_align.bam
samtools view -bS sample_OFF005_align.sam > sample_OFF005_align.bam
samtools view -bS sample_OFF006_align.sam > sample_OFF006_align.bam
samtools view -bS sample_OFF007_align.sam > sample_OFF007_align.bam
samtools view -bS sample_OFF008_align.sam > sample_OFF008_align.bam
samtools view -bS sample_OFF009_align.sam > sample_OFF009_align.bam
samtools view -bS sample_OFF010_align.sam > sample_OFF010_align.bam
samtools view -bS sample_OFF011_align.sam > sample_OFF011_align.bam
samtools view -bS sample_OFF012_align.sam > sample_OFF012_align.bam
samtools view -bS sample_OFF013_align.sam > sample_OFF013_align.bam
samtools view -bS sample_OFF014_align.sam > sample_OFF014_align.bam
samtools view -bS sample_OFF015_align.sam > sample_OFF015_align.bam
samtools view -bS sample_OFF016-1_align.sam > sample_OFF016-1_align.bam
samtools view -bS sample_OFF016_align.sam > sample_OFF016_align.bam
samtools view -bS sample_OFF017_align.sam > sample_OFF017_align.bam
samtools view -bS sample_OFF018_align.sam > sample_OFF018_align.bam
samtools view -bS sample_OFF020_align.sam > sample_OFF020_align.bam
samtools view -bS sample_OFF022_align.sam > sample_OFF022_align.bam
samtools view -bS sample_OFF024_align.sam > sample_OFF024_align.bam
samtools view -bS sample_OFF025_align.sam > sample_OFF025_align.bam
samtools view -bS sample_OFF026_align.sam > sample_OFF026_align.bam
samtools view -bS sample_OFF027-1_align.sam > sample_OFF027-1_align.bam
samtools view -bS sample_OFF027_align.sam > sample_OFF027_align.bam
samtools view -bS sample_OFF028_align.sam > sample_OFF028_align.bam
samtools view -bS sample_OFF029_align.sam > sample_OFF029_align.bam
samtools view -bS sample_OFF030_align.sam > sample_OFF030_align.bam
samtools view -bS sample_OFF031_align.sam > sample_OFF031_align.bam
samtools view -bS sample_OFF032-1_align.sam > sample_OFF032-1_align.bam
samtools view -bS sample_OFF032_align.sam > sample_OFF032_align.bam
samtools view -bS sample_OFF033_align.sam > sample_OFF033_align.bam
samtools view -bS sample_OFF034_align.sam > sample_OFF034_align.bam
samtools view -bS sample_OFF035_align.sam > sample_OFF035_align.bam
samtools view -bS sample_OFF036_align.sam > sample_OFF036_align.bam
samtools view -bS sample_OFF037_align.sam > sample_OFF037_align.bam
samtools view -bS sample_OFF038_align.sam > sample_OFF038_align.bam
samtools view -bS sample_OFF039_align.sam > sample_OFF039_align.bam
samtools view -bS sample_OFF041_align.sam > sample_OFF041_align.bam
samtools view -bS sample_OFF042_align.sam > sample_OFF042_align.bam
samtools view -bS sample_OFF043_align.sam > sample_OFF043_align.bam
samtools view -bS sample_OFF044_align.sam > sample_OFF044_align.bam
samtools view -bS sample_OFF045_align.sam > sample_OFF045_align.bam
samtools view -bS sample_OFF046_align.sam > sample_OFF046_align.bam
samtools view -bS sample_OFF047_align.sam > sample_OFF047_align.bam
samtools view -bS sample_OFF049_align.sam > sample_OFF049_align.bam
samtools view -bS sample_OFF050_align.sam > sample_OFF050_align.bam
samtools view -bS sample_OFF051_align.sam > sample_OFF051_align.bam
samtools view -bS sample_OFF052_align.sam > sample_OFF052_align.bam
samtools view -bS sample_OFF053_align.sam > sample_OFF053_align.bam
samtools view -bS sample_OFF054_align.sam > sample_OFF054_align.bam
samtools view -bS sample_OFF055_align.sam > sample_OFF055_align.bam
samtools view -bS sample_OFF056_align.sam > sample_OFF056_align.bam
samtools view -bS sample_OFF057_align.sam > sample_OFF057_align.bam
samtools view -bS sample_OFF058_align.sam > sample_OFF058_align.bam
samtools view -bS sample_OFF059_align.sam > sample_OFF059_align.bam
samtools view -bS sample_OFF060_align.sam > sample_OFF060_align.bam
samtools view -bS sample_OFF061_align.sam > sample_OFF061_align.bam
samtools view -bS sample_OFF064_align.sam > sample_OFF064_align.bam
samtools view -bS sample_OFF066_align.sam > sample_OFF066_align.bam
samtools view -bS sample_OFF067_align.sam > sample_OFF067_align.bam
samtools view -bS sample_OFF068_align.sam > sample_OFF068_align.bam
samtools view -bS sample_OFF070_align.sam > sample_OFF070_align.bam
samtools view -bS sample_OFF071_align.sam > sample_OFF071_align.bam
samtools view -bS sample_OFF072_align.sam > sample_OFF072_align.bam
samtools view -bS sample_OFF073_align.sam > sample_OFF073_align.bam
samtools view -bS sample_OFF074_align.sam > sample_OFF074_align.bam
samtools view -bS sample_OFF075_align.sam > sample_OFF075_align.bam
samtools view -bS sample_OFF076_align.sam > sample_OFF076_align.bam
samtools view -bS sample_OFF077_align.sam > sample_OFF077_align.bam
samtools view -bS sample_OFF078_align.sam > sample_OFF078_align.bam
samtools view -bS sample_OFF079_align.sam > sample_OFF079_align.bam
samtools view -bS sample_OFF080_align.sam > sample_OFF080_align.bam
samtools view -bS sample_OFF081_align.sam > sample_OFF081_align.bam
samtools view -bS sample_OFF083_align.sam > sample_OFF083_align.bam
samtools view -bS sample_OFF084_align.sam > sample_OFF084_align.bam
samtools view -bS sample_OFF085_align.sam > sample_OFF085_align.bam
samtools view -bS sample_OFF08623_align.sam > sample_OFF08623_align.bam
samtools view -bS sample_OFF086_align.sam > sample_OFF086_align.bam
samtools view -bS sample_OFF088_align.sam > sample_OFF088_align.bam
samtools view -bS sample_OFF089_align.sam > sample_OFF089_align.bam
samtools view -bS sample_OFF090_align.sam > sample_OFF090_align.bam
samtools view -bS sample_OFF091_align.sam > sample_OFF091_align.bam
samtools view -bS sample_OFF092_align.sam > sample_OFF092_align.bam
samtools view -bS sample_OFF093_align.sam > sample_OFF093_align.bam
samtools view -bS sample_OFF094_align.sam > sample_OFF094_align.bam
samtools view -bS sample_OFF095_align.sam > sample_OFF095_align.bam
samtools view -bS sample_OFF096_align.sam > sample_OFF096_align.bam
samtools view -bS sample_OFF097_align.sam > sample_OFF097_align.bam
samtools view -bS sample_OFF100_align.sam > sample_OFF100_align.bam
samtools view -bS sample_OFF101_align.sam > sample_OFF101_align.bam
samtools view -bS sample_OFF102_align.sam > sample_OFF102_align.bam
samtools view -bS sample_OFF103_align.sam > sample_OFF103_align.bam
samtools view -bS sample_OFF105_align.sam > sample_OFF105_align.bam
samtools view -bS sample_OFF106_align.sam > sample_OFF106_align.bam
samtools view -bS sample_OFF110_align.sam > sample_OFF110_align.bam
samtools view -bS sample_OFF111_align.sam > sample_OFF111_align.bam
samtools view -bS sample_OFF112_align.sam > sample_OFF112_align.bam
samtools view -bS sample_OFF113_align.sam > sample_OFF113_align.bam
samtools view -bS sample_OFF114_align.sam > sample_OFF114_align.bam
samtools view -bS sample_OFF115_align.sam > sample_OFF115_align.bam
samtools view -bS sample_OFF117_align.sam > sample_OFF117_align.bam
samtools view -bS sample_OFF118_align.sam > sample_OFF118_align.bam
samtools view -bS sample_OFF119_align.sam > sample_OFF119_align.bam
samtools view -bS sample_OFF120_align.sam > sample_OFF120_align.bam
samtools view -bS sample_OFF121_align.sam > sample_OFF121_align.bam
samtools view -bS sample_OFF122_align.sam > sample_OFF122_align.bam
samtools view -bS sample_OFF123_align.sam > sample_OFF123_align.bam
samtools view -bS sample_OFF124_align.sam > sample_OFF124_align.bam
samtools view -bS sample_OFF125_align.sam > sample_OFF125_align.bam
samtools view -bS sample_OFF126_align.sam > sample_OFF126_align.bam
samtools view -bS sample_OFF127_align.sam > sample_OFF127_align.bam
samtools view -bS sample_OFF134_align.sam > sample_OFF134_align.bam
samtools view -bS sample_OFF135_align.sam > sample_OFF135_align.bam
samtools view -bS sample_OFF136_align.sam > sample_OFF136_align.bam
samtools view -bS sample_OFF137_align.sam > sample_OFF137_align.bam
samtools view -bS sample_OFF138_align.sam > sample_OFF138_align.bam
samtools view -bS sample_OFF139_align.sam > sample_OFF139_align.bam
samtools view -bS sample_OFF140_align.sam > sample_OFF140_align.bam
samtools view -bS sample_OFF142_align.sam > sample_OFF142_align.bam
samtools view -bS sample_OFF143_align.sam > sample_OFF143_align.bam
samtools view -bS sample_OFF144_align.sam > sample_OFF144_align.bam
samtools view -bS sample_OFF145_align.sam > sample_OFF145_align.bam
samtools view -bS sample_OFF146_align.sam > sample_OFF146_align.bam
samtools view -bS sample_OFF149_align.sam > sample_OFF149_align.bam
samtools view -bS sample_OFF150_align.sam > sample_OFF150_align.bam
samtools view -bS sample_OFF151_align.sam > sample_OFF151_align.bam
samtools view -bS sample_OFF152_align.sam > sample_OFF152_align.bam
samtools view -bS sample_OFF153_align.sam > sample_OFF153_align.bam
samtools view -bS sample_OFF154_align.sam > sample_OFF154_align.bam
samtools view -bS sample_OFF155_align.sam > sample_OFF155_align.bam
samtools view -bS sample_OFF156_align.sam > sample_OFF156_align.bam
samtools view -bS sample_OFF157_align.sam > sample_OFF157_align.bam
samtools view -bS sample_OFF158_align.sam > sample_OFF158_align.bam
samtools view -bS sample_OFF159_align.sam > sample_OFF159_align.bam
samtools view -bS sample_OFF160_align.sam > sample_OFF160_align.bam
samtools view -bS sample_OFF161_align.sam > sample_OFF161_align.bam
samtools view -bS sample_OFF165_align.sam > sample_OFF165_align.bam
samtools view -bS sample_OFF166_align.sam > sample_OFF166_align.bam
samtools view -bS sample_OFF167_align.sam > sample_OFF167_align.bam
samtools view -bS sample_OFF168_align.sam > sample_OFF168_align.bam
samtools view -bS sample_OFF169_align.sam > sample_OFF169_align.bam
samtools view -bS sample_OFF170_align.sam > sample_OFF170_align.bam
samtools view -bS sample_OFF171_align.sam > sample_OFF171_align.bam
samtools view -bS sample_OFF172_align.sam > sample_OFF172_align.bam
samtools view -bS sample_OFF173_align.sam > sample_OFF173_align.bam
samtools view -bS sample_OFF174_align.sam > sample_OFF174_align.bam
samtools view -bS sample_OFF175_align.sam > sample_OFF175_align.bam
samtools view -bS sample_OFF176_align.sam > sample_OFF176_align.bam
samtools view -bS sample_OFF177_align.sam > sample_OFF177_align.bam
samtools view -bS sample_OFF178_align.sam > sample_OFF178_align.bam
samtools view -bS sample_OFF179_align.sam > sample_OFF179_align.bam
samtools view -bS sample_OFF181_align.sam > sample_OFF181_align.bam
samtools view -bS sample_OFF182_align.sam > sample_OFF182_align.bam
samtools view -bS sample_OFF183_align.sam > sample_OFF183_align.bam
samtools view -bS sample_OFF184_align.sam > sample_OFF184_align.bam
samtools view -bS sample_OFF185_align.sam > sample_OFF185_align.bam
samtools view -bS sample_OFF186_align.sam > sample_OFF186_align.bam
samtools view -bS sample_OFF187_align.sam > sample_OFF187_align.bam
samtools view -bS sample_OFF188_align.sam > sample_OFF188_align.bam
samtools view -bS sample_OFF189_align.sam > sample_OFF189_align.bam
samtools view -bS sample_PRM001_align.sam > sample_PRM001_align.bam
samtools view -bS sample_PRM002_align.sam > sample_PRM002_align.bam
samtools view -bS sample_PRM003_align.sam > sample_PRM003_align.bam
samtools view -bS sample_PRM005_align.sam > sample_PRM005_align.bam
samtools view -bS sample_PRM006_align.sam > sample_PRM006_align.bam
samtools view -bS sample_PRM007_align.sam > sample_PRM007_align.bam
samtools view -bS sample_PRM009_align.sam > sample_PRM009_align.bam
samtools view -bS sample_PRM010_align.sam > sample_PRM010_align.bam
samtools view -bS sample_PRM011_align.sam > sample_PRM011_align.bam
samtools view -bS sample_PRM012_align.sam > sample_PRM012_align.bam
samtools view -bS sample_PRM013_align.sam > sample_PRM013_align.bam
samtools view -bS sample_PRM014_align.sam > sample_PRM014_align.bam
samtools view -bS sample_PRM015_align.sam > sample_PRM015_align.bam
samtools view -bS sample_PRM016_align.sam > sample_PRM016_align.bam
samtools view -bS sample_PRM017_align.sam > sample_PRM017_align.bam
samtools view -bS sample_PRM018_align.sam > sample_PRM018_align.bam
samtools view -bS sample_PRM019_align.sam > sample_PRM019_align.bam
samtools view -bS sample_PRM022_align.sam > sample_PRM022_align.bam
samtools view -bS sample_PRM023_align.sam > sample_PRM023_align.bam
samtools view -bS sample_PRM024_align.sam > sample_PRM024_align.bam
samtools view -bS sample_PRM025_align.sam > sample_PRM025_align.bam
samtools view -bS sample_PRM026_align.sam > sample_PRM026_align.bam
samtools view -bS sample_PRM027_align.sam > sample_PRM027_align.bam
samtools view -bS sample_PRM028_align.sam > sample_PRM028_align.bam
samtools view -bS sample_PRM029_align.sam > sample_PRM029_align.bam
samtools view -bS sample_PRM030_align.sam > sample_PRM030_align.bam
samtools view -bS sample_PRM031_align.sam > sample_PRM031_align.bam
samtools view -bS sample_PRM032_align.sam > sample_PRM032_align.bam
samtools view -bS sample_PRM033_align.sam > sample_PRM033_align.bam
samtools view -bS sample_PRM034_align.sam > sample_PRM034_align.bam
samtools view -bS sample_PRM035-1_align.sam > sample_PRM035-1_align.bam
samtools view -bS sample_PRM035-2_align.sam > sample_PRM035-2_align.bam
samtools view -bS sample_PRM036_align.sam > sample_PRM036_align.bam
samtools view -bS sample_PRM037_align.sam > sample_PRM037_align.bam
samtools view -bS sample_PRM038_align.sam > sample_PRM038_align.bam
samtools view -bS sample_PRM039_align.sam > sample_PRM039_align.bam
samtools view -bS sample_PRM040_align.sam > sample_PRM040_align.bam
samtools view -bS sample_PRM041_align.sam > sample_PRM041_align.bam
samtools view -bS sample_PRM042_align.sam > sample_PRM042_align.bam
samtools view -bS sample_PRM043_align.sam > sample_PRM043_align.bam
samtools view -bS sample_PRM044_align.sam > sample_PRM044_align.bam
samtools view -bS sample_PRM045_align.sam > sample_PRM045_align.bam
samtools view -bS sample_PRM046_align.sam > sample_PRM046_align.bam
samtools view -bS sample_PRM047_align.sam > sample_PRM047_align.bam
samtools view -bS sample_PRM048_align.sam > sample_PRM048_align.bam
samtools view -bS sample_PRM049_align.sam > sample_PRM049_align.bam
samtools view -bS sample_PRM050_align.sam > sample_PRM050_align.bam
samtools view -bS sample_PRM051_align.sam > sample_PRM051_align.bam
samtools view -bS sample_PRM052_align.sam > sample_PRM052_align.bam
samtools view -bS sample_PRM053_align.sam > sample_PRM053_align.bam
samtools view -bS sample_PRM054_align.sam > sample_PRM054_align.bam
samtools view -bS sample_PRM055_align.sam > sample_PRM055_align.bam
samtools view -bS sample_PRM056_align.sam > sample_PRM056_align.bam
samtools view -bS sample_PRM057_align.sam > sample_PRM057_align.bam
samtools view -bS sample_PRM058_align.sam > sample_PRM058_align.bam
samtools view -bS sample_PRM059_align.sam > sample_PRM059_align.bam
samtools view -bS sample_PRM060_align.sam > sample_PRM060_align.bam
samtools view -bS sample_PRM061_align.sam > sample_PRM061_align.bam
samtools view -bS sample_PRM062_align.sam > sample_PRM062_align.bam
samtools view -bS sample_PRM063_align.sam > sample_PRM063_align.bam
samtools view -bS sample_PRM064_align.sam > sample_PRM064_align.bam
samtools view -bS sample_PRM065_align.sam > sample_PRM065_align.bam
samtools view -bS sample_PRM066_align.sam > sample_PRM066_align.bam
samtools view -bS sample_PRM067_align.sam > sample_PRM067_align.bam
samtools view -bS sample_PRM068_align.sam > sample_PRM068_align.bam
samtools view -bS sample_PRM069_align.sam > sample_PRM069_align.bam
samtools view -bS sample_PRM070_align.sam > sample_PRM070_align.bam
samtools view -bS sample_PRM071_align.sam > sample_PRM071_align.bam
samtools view -bS sample_PRM072_align.sam > sample_PRM072_align.bam
samtools view -bS sample_PRM073_align.sam > sample_PRM073_align.bam
samtools view -bS sample_PRM074_align.sam > sample_PRM074_align.bam
samtools view -bS sample_PRM075_align.sam > sample_PRM075_align.bam
samtools view -bS sample_PRM076_align.sam > sample_PRM076_align.bam
samtools view -bS sample_PRM077_align.sam > sample_PRM077_align.bam
samtools view -bS sample_PRM078_align.sam > sample_PRM078_align.bam
samtools view -bS sample_PRM079_align.sam > sample_PRM079_align.bam
samtools view -bS sample_PRM080_align.sam > sample_PRM080_align.bam
samtools view -bS sample_PRM081_align.sam > sample_PRM081_align.bam
samtools view -bS sample_PRM082_align.sam > sample_PRM082_align.bam
samtools view -bS sample_PRM083_align.sam > sample_PRM083_align.bam
samtools view -bS sample_PRM084_align.sam > sample_PRM084_align.bam
samtools view -bS sample_PRM085_align.sam > sample_PRM085_align.bam
samtools view -bS sample_PRM086-23_align.sam > sample_PRM086-23_align.bam
samtools view -bS sample_PRM086R_align.sam > sample_PRM086R_align.bam
samtools view -bS sample_PRM087_align.sam > sample_PRM087_align.bam
samtools view -bS sample_PRM088_align.sam > sample_PRM088_align.bam
samtools view -bS sample_PRM089_align.sam > sample_PRM089_align.bam
samtools view -bS sample_PRM090_align.sam > sample_PRM090_align.bam
samtools view -bS sample_PRM091_align.sam > sample_PRM091_align.bam
samtools view -bS sample_PRM092_align.sam > sample_PRM092_align.bam
samtools view -bS sample_PRM093_align.sam > sample_PRM093_align.bam
samtools view -bS sample_PRM094_align.sam > sample_PRM094_align.bam
samtools view -bS sample_PRM095_align.sam > sample_PRM095_align.bam
samtools view -bS sample_PRM096_align.sam > sample_PRM096_align.bam
samtools view -bS sample_PRM097_align.sam > sample_PRM097_align.bam
samtools view -bS sample_PRM098_align.sam > sample_PRM098_align.bam
samtools view -bS sample_PRM099_align.sam > sample_PRM099_align.bam
samtools view -bS sample_PRM100_align.sam > sample_PRM100_align.bam
samtools view -bS sample_PRM101_align.sam > sample_PRM101_align.bam
samtools view -bS sample_PRM102_align.sam > sample_PRM102_align.bam
samtools view -bS sample_PRM103_align.sam > sample_PRM103_align.bam
samtools view -bS sample_PRM104_align.sam > sample_PRM104_align.bam
samtools view -bS sample_PRM105_align.sam > sample_PRM105_align.bam
samtools view -bS sample_PRM106_align.sam > sample_PRM106_align.bam
samtools view -bS sample_PRM107_align.sam > sample_PRM107_align.bam
samtools view -bS sample_PRM108_align.sam > sample_PRM108_align.bam
samtools view -bS sample_PRM109_align.sam > sample_PRM109_align.bam
samtools view -bS sample_PRM110_align.sam > sample_PRM110_align.bam
samtools view -bS sample_PRM111_align.sam > sample_PRM111_align.bam
samtools view -bS sample_PRM112_align.sam > sample_PRM112_align.bam
samtools view -bS sample_PRM113_align.sam > sample_PRM113_align.bam
samtools view -bS sample_PRM114_align.sam > sample_PRM114_align.bam
samtools view -bS sample_PRM115_align.sam > sample_PRM115_align.bam
samtools view -bS sample_PRM116_align.sam > sample_PRM116_align.bam
samtools view -bS sample_PRM117_align.sam > sample_PRM117_align.bam
samtools view -bS sample_PRM118_align.sam > sample_PRM118_align.bam
samtools view -bS sample_PRM119_align.sam > sample_PRM119_align.bam
samtools view -bS sample_PRM120_align.sam > sample_PRM120_align.bam
samtools view -bS sample_PRM121_align.sam > sample_PRM121_align.bam
samtools view -bS sample_PRM122_align.sam > sample_PRM122_align.bam
samtools view -bS sample_PRM123_align.sam > sample_PRM123_align.bam
samtools view -bS sample_PRM124_align.sam > sample_PRM124_align.bam
samtools view -bS sample_PRM125_align.sam > sample_PRM125_align.bam
samtools view -bS sample_PRM126_align.sam > sample_PRM126_align.bam
samtools view -bS sample_PRM127_align.sam > sample_PRM127_align.bam
samtools view -bS sample_PRM128_align.sam > sample_PRM128_align.bam
samtools view -bS sample_PRM129_align.sam > sample_PRM129_align.bam
samtools view -bS sample_PRM130_align.sam > sample_PRM130_align.bam
samtools view -bS sample_PRM131_align.sam > sample_PRM131_align.bam
samtools view -bS sample_PRM132_align.sam > sample_PRM132_align.bam
samtools view -bS sample_PRM133_align.sam > sample_PRM133_align.bam
samtools view -bS sample_PRM134_align.sam > sample_PRM134_align.bam
samtools view -bS sample_PRM135_align.sam > sample_PRM135_align.bam
samtools view -bS sample_PRM136_align.sam > sample_PRM136_align.bam
samtools view -bS sample_PRM137_align.sam > sample_PRM137_align.bam
samtools view -bS sample_PRM138_align.sam > sample_PRM138_align.bam
samtools view -bS sample_PRM139_align.sam > sample_PRM139_align.bam
samtools view -bS sample_PRM140_align.sam > sample_PRM140_align.bam
samtools view -bS sample_PRM141_align.sam > sample_PRM141_align.bam
samtools view -bS sample_PRM142_align.sam > sample_PRM142_align.bam
samtools view -bS sample_PRM143_align.sam > sample_PRM143_align.bam
samtools view -bS sample_PRM144_align.sam > sample_PRM144_align.bam
samtools view -bS sample_PRM145_align.sam > sample_PRM145_align.bam
samtools view -bS sample_PRM146_align.sam > sample_PRM146_align.bam
samtools view -bS sample_PRM147_align.sam > sample_PRM147_align.bam
samtools view -bS sample_PRM148_align.sam > sample_PRM148_align.bam
samtools view -bS sample_PRM149_align.sam > sample_PRM149_align.bam
samtools view -bS sample_PRM150_align.sam > sample_PRM150_align.bam
samtools view -bS sample_PRM151_align.sam > sample_PRM151_align.bam
samtools view -bS sample_PRM152_align.sam > sample_PRM152_align.bam
samtools view -bS sample_PRM153_align.sam > sample_PRM153_align.bam
samtools view -bS sample_PRM154_align.sam > sample_PRM154_align.bam
samtools view -bS sample_PRM155_align.sam > sample_PRM155_align.bam
samtools view -bS sample_PRM156_align.sam > sample_PRM156_align.bam
samtools view -bS sample_PRM157_align.sam > sample_PRM157_align.bam
samtools view -bS sample_PRM158_align.sam > sample_PRM158_align.bam
samtools view -bS sample_PRM159_align.sam > sample_PRM159_align.bam
samtools view -bS sample_PRM160_align.sam > sample_PRM160_align.bam
samtools view -bS sample_PRM161_align.sam > sample_PRM161_align.bam
samtools view -bS sample_PRM162_align.sam > sample_PRM162_align.bam
samtools view -bS sample_PRM163_align.sam > sample_PRM163_align.bam
samtools view -bS sample_PRM164_align.sam > sample_PRM164_align.bam
samtools view -bS sample_PRM165_align.sam > sample_PRM165_align.bam
samtools view -bS sample_PRM166_align.sam > sample_PRM166_align.bam
samtools view -bS sample_PRM167_align.sam > sample_PRM167_align.bam
samtools view -bS sample_PRM168_align.sam > sample_PRM168_align.bam
samtools view -bS sample_PRM169_align.sam > sample_PRM169_align.bam
samtools view -bS sample_PRM170_align.sam > sample_PRM170_align.bam
samtools view -bS sample_PRM171_align.sam > sample_PRM171_align.bam
samtools view -bS sample_PRM172_align.sam > sample_PRM172_align.bam
samtools view -bS sample_PRM173_align.sam > sample_PRM173_align.bam
samtools view -bS sample_PRM174_align.sam > sample_PRM174_align.bam
samtools view -bS sample_PRM175_align.sam > sample_PRM175_align.bam
samtools view -bS sample_PRM176_align.sam > sample_PRM176_align.bam
samtools view -bS sample_PRM177-1_align.sam > sample_PRM177-1_align.bam
samtools view -bS sample_PRM177_align.sam > sample_PRM177_align.bam
samtools view -bS sample_PRM178_align.sam > sample_PRM178_align.bam
samtools view -bS sample_PRM179_align.sam > sample_PRM179_align.bam
samtools view -bS sample_PRM180_align.sam > sample_PRM180_align.bam
samtools view -bS sample_PRM181_align.sam > sample_PRM181_align.bam
samtools view -bS sample_PRM182_align.sam > sample_PRM182_align.bam
samtools view -bS sample_PRM183_align.sam > sample_PRM183_align.bam
samtools view -bS sample_PRM184_align.sam > sample_PRM184_align.bam
samtools view -bS sample_PRM185_align.sam > sample_PRM185_align.bam
samtools view -bS sample_PRM186_align.sam > sample_PRM186_align.bam
samtools view -bS sample_PRM187_align.sam > sample_PRM187_align.bam
samtools view -bS sample_PRM188_align.sam > sample_PRM188_align.bam
samtools view -bS sample_PRM189_align.sam > sample_PRM189_align.bam
